# Generated by Django 5.2.4 on 2025-11-12 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Zgloszenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=255)),
                ('opis', models.TextField()),
                ('status', models.CharField(choices=[('NOWE', 'Nowe'), ('W_TOKU', 'W toku'), ('ROZWIAZANE', 'Rozwiązane')], default='NOWE', max_length=20)),
                ('priorytet', models.CharField(choices=[('NISKI', 'Niski'), ('SREDNI', 'Średni'), ('WYSOKI', 'Wysoki')], default='SREDNI', max_length=20)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('data_aktualizacji', models.DateTimeField(auto_now=True)),
                ('kategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk.kategoria')),
                ('przypisane_do', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='przypisane_zgloszenia', to=settings.AUTH_USER_MODEL)),
                ('zgloszone_przez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moje_zgloszenia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zgloszenie',
                'verbose_name_plural': 'Zgloszenia',
                'ordering': ['-data_utworzenia'],
            },
        ),
        migrations.CreateModel(
            name='Komentarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zgloszenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentarze', to='helpdesk.zgloszenie')),
            ],
            options={
                'verbose_name': 'Komentarz',
                'verbose_name_plural': 'Komentarze',
                'ordering': ['data_dodania'],
            },
        ),
    ]
